export const fielddatamap = [
  {
    id: "customTaxCode",
    name: "customTaxCode",
    placeholder: "Enter Custom Tax Code",
    type: "text",
    label: "Custom Tax Code",
    initialvalue: "",
    required: true,
    errmsg: "Custom Tax Code is required",
    minlength: 1,
    maxlength: 25,
    datatype: ["AN"], //["N","S","AN","ARR","B","D"],
    validatefor: "" //["email", "url"]
  },
  {
    id: "customTaxName",
    name: "customTaxName",
    placeholder: "Enter Custom Tax Name",
    type: "text",
    label: "Custom Tax Name",
    initialvalue: "",
    required: true,
    errmsg: "Custom Tax Name is required",
    minlength: 1,
    maxlength: 25,
    datatype: ["AN"],
    validatefor: "" //["email", "url"]
  },
  {
    id: "taxCodeAutoCompl",
    name: "taxCodeAutoCompl",
    placeholder: "Select Tax Code",
    type: "select",
    label: "Tax Code",
    initialvalue: "",
    required: true,
    errmsg: "Tax Code may not be blank.",
    options: "",
    autocomplete: true,
    isasync: true,
    multiselect: false
  },
  {
    id: "taxTypeAutocomplete",
    name: "taxTypeAutocomplete",
    placeholder: "Select Tax Type",
    type: "select",
    label: "Tax Type",
    initialvalue: "",
    required: true,
    errmsg: "Tax Type may not be blank.",
    options: "",
    autocomplete: true,
    isasync: true,
    multiselect: false
  },
  {
    id: "formulaNumber",
    name: "formulaNumber",
    placeholder: "",
    type: "text",
    label: "Formula Number",
    initialvalue: "",
    required: true,
    errmsg: "Invalid Formula Number. Defaulting to 0.",
    minlength: 0,
    maxlength: 3,
    datatype: ["N"],
    validatefor: "" //["email", "url"]
  },
  {
    id: "startDate",
    name: "startDate",
    placeholder: "",
    type: "text",
    label: "Start Date",
    initialvalue: "",
    required: true,
    errmsg: "Start Date value is invalid.",
    minlength: 0,
    maxlength: 3,
    datatype: ["D"],
    validatefor: "" //["email", "url"]
  },
  {
    id: "companyCodeAutoCompl",
    name: "companyCodeAutoCompl",
    placeholder: "",
    type: "select",
    label: "Company Code",
    initialvalue: "",
    required: true,
    errmsg: "",
    options: "",
    autocomplete: true,
    isasync: true,
    multiselect: false
  },
  {
    id: "riskClassAutoCompl",
    name: "riskClassAutoCompl",
    placeholder: "",
    type: "select",
    label: "Risk Class",
    initialvalue: "",
    required: false,
    errmsg: "",
    options: "",
    autocomplete: true,
    isasync: true,
    multiselect: false
  }
];